# Generated by Django 3.1.5 on 2021-01-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='fullname',
            field=models.CharField(default='NONAME', max_length=75),
        ),
    ]
