# Generated by Django 3.1.5 on 2021-01-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210110_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
