# Generated by Django 3.1.5 on 2021-01-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210110_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_info',
            name='photo',
        ),
        migrations.AddField(
            model_name='book_info',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
