# Generated by Django 3.1.5 on 2021-01-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210110_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
