# Generated by Django 3.1.5 on 2021-01-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210110_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='image',
            field=models.ImageField(upload_to='C:\\projects\\test_task\\main_app\\media'),
        ),
    ]
